# Generated by Django 5.0.2 on 2024-03-15 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_report_date_report_date_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
