# Generated by Django 5.0.2 on 2024-03-28 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report_admin_notes_report_is_in_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='admin_notes',
            field=models.TextField(),
        ),
    ]
