# Generated by Django 5.0.2 on 2024-03-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_document_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='document',
        ),
        migrations.AddField(
            model_name='report',
            name='document',
            field=models.ManyToManyField(to='main.document'),
        ),
    ]
