# Generated by Django 5.0.2 on 2024-03-11 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customuser_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='school',
            new_name='school_membership',
        ),
    ]
