# Generated by Django 5.0.2 on 2024-03-12 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_school_customuser_school_membership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='school_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.school'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('message_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to='main.messageboard')),
            ],
        ),
    ]
